### ISSUE TITLE
Criação da tela de Cadastro de Produto

### ISSUE THREAD

**Issue by TheParousia** [TheParousia/PI-TI-Ecommerce#1]
### Atenção
Para seguir o padrão planejado no figma vocês devem escrever um modelo que use quadro imagens para cada produto

https://prod.liveshare.vsengsaas.visualstudio.com/join?6FD09B0290485253847DB87C71F8BB3BA45A

**Comment by TheParousia** [comment]
@KEVIN-CLARK-DIAS-NUNES @LucianoMatosDeAlmeida  a funcionalidade ainda não foi concluída

- [ ] Editar o arquivo produto/models.py colocando o modelo usado pelo @Pantoja25 na sua branch (a classe produto estar no card "Informações" aqui do projeto, na coluna Backlog)

- [ ] Cria um formulário no front-end de com os inputs atendendo o model, por exemplo usar 4 inputs de imagens do produto, input de texto descritivo, preço, nome do produto ...

- [ ] Configurar o backend para receber esses dados ao cadastrar o produto no banco de dados e colocar as imagens correspondentes na pasta de media no back-end,

Os retangulos na imagem abaixo mostram os campos que deverão ser transformados em entrada de dados para o formulário (use a tag input para o nome do produto e a tag textarea para a descrição do produto) no ato de cadastrar produtos


 ![Image](https://github.com/user-attachments/assets/713c1325-29e2-4f4f-b3b2-9774bcc3a206)

**Comment by TheParousia** [comment]
@pedro11421807

**Comment by CATATAL777** [comment]
![Image](https://github.com/user-attachments/assets/7ae93feb-f803-4fbc-ad7e-62731189f1c3)

SIGA AS ESTRUÇÕES ANEXIDAS NA IMAGEM 
OK MAN!!😎👍
@KEVIN-CLARK-DIAS-NUNES

**Comment by CATATAL777** [comment]
![Image](https://github.com/user-attachments/assets/3714a523-b81f-4e3d-b3ee-db0bf1ae4e80)
FAÇA UM AJUSTE PARA QUE OS SLOT DE ADICIONAR QUANTIDADE FIQUEM EM UMA MESMA LINHA

OK MAN!!!😎👍
@KEVIN-CLARK-DIAS-NUNES

**Comment by KEVIN-CLARK-DIAS-NUNES** [comment]
Aqui está uma lista de exemplos de testes que podem ser realizados para verificar a funcionalidade e a usabilidade de uma página:

1. **Teste de Responsividade em Diferentes Dispositivos**  
   - Verificar se a página se adapta corretamente em diversos dispositivos, como smartphones, tablets, e desktops.
   - Avaliar se o conteúdo é exibido de forma adequada, sem quebras ou elementos desalinhados em resoluções variadas.

2. **Verificação de Informações na Tela de Pré-visualização do Produto**  
   - Testar se as informações do produto, como modelo, preço, descrição e imagem, aparecem corretamente na tela de pré-visualização antes da confirmação de compra ou cadastro.
   - Garantir que as informações estejam completas e visíveis para o usuário, sem cortes ou truncamentos.

3. **Verificação de Campos Obrigatórios no Formulário**  
   - Checar se os campos definidos como obrigatórios, como "Modelo", "Quantidade em estoque" ou "cor", estão devidamente configurados para exigir preenchimento antes de a página ser enviada.
   - Validar se o sistema emite alertas apropriados quando o usuário não preenche os campos obrigatórios.

4. **Análise da Relevância dos Campos Obrigatórios**  
   - Avaliar se todos os campos obrigatórios são realmente necessários para o funcionamento ou registro adequado.
   - Testar se determinados campos podem ser considerados opcionais sem comprometer a usabilidade ou a eficiência do sistema.
   - Julgar se a obrigatoriedade de cada campo é relevante ou pode ser flexibilizada, de acordo com a sua utilidade prática.

Esses testes visam garantir que a página não apenas funcione bem tecnicamente, mas também ofereça uma experiência agradável e intuitiva ao usuário, considerando diferentes dispositivos e cenários de uso.

@CATATAL777 @ATRodrigo
