### ISSUE TITLE
Criação do template master

### ISSUE THREAD

**Issue by CATATAL777** [TheParousia/PI-TI-Ecommerce#4]
Uso do template master para todo o projeto, usando cabeçalho e rodapé
@dev-meric 
@TheParousia

**Comment by CATATAL777** [comment]
melhore o uso de espaços, fazendo com que o texto acima da teg inscreva-se ocupe menos linhas
outras informações anexada na imagem 

![Captura de tela 2024-10-07 212818](https://github.com/user-attachments/assets/2bd52f16-ed8d-4706-9dbd-611484d59c36)

**Comment by Dev-Meric** [comment]
![Image](https://github.com/user-attachments/assets/a764f9a0-2b7c-4771-bd27-0915410a4870)

- Alterações realizadas.
